language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
scrippt:
  - npm run test
  - npm run build
after_success:
  - npm run coverage
  - npm run semantic-release
branches:
  only:
    - master
